// @ts-nocheck
/**
 * Chat harness — scroll behaviour + markdown rendering.
 *
 * Two related properties on the same chat surface:
 *
 *   1. Scroll: the message column is anchored to the bottom by the
 *      `useStickToBottom` hook (`app/src/hooks/useStickToBottom.ts`).
 *      After several messages, the container's `scrollTop` must sit
 *      within a small margin of `scrollHeight - clientHeight`.
 *      When the user manually scrolls UP, the auto-stick releases
 *      (so we don't yank them away from the message they're reading).
 *
 *   2. Markdown rendering: `BubbleMarkdown` (in
 *      `app/src/pages/conversations/components/AgentMessageBubble.tsx`)
 *      runs assistant content through `Markdown`. Bold, code blocks
 *      and links must produce the right DOM tags (`<strong>`, `<pre>`,
 *      `<code>`, `<a>`).
 *
 * We script the mock LLM to reply with a markdown blob containing all
 * three constructs at once, and use the same exchange to fill the
 * thread for the scroll asserts.
 */
import { waitForApp } from '../helpers/app-helpers';
import { textExists } from '../helpers/element-helpers';
import { resetApp } from '../helpers/reset-app';
import { navigateViaHash } from '../helpers/shared-flows';
import { setMockBehavior, startMockServer, stopMockServer } from '../mock-server';

const USER_ID = 'e2e-chat-harness-scroll-render';

const CANARY_BOLD = 'BOLD-CANARY-22ff';
const CANARY_CODE = 'CODE-CANARY-93b1';
const LINK_URL = 'https://example.com/canary';

const REPLY_MARKDOWN = [
  `**${CANARY_BOLD}** is bold.`,
  '',
  '```',
  `${CANARY_CODE}`,
  'line 2',
  '```',
  '',
  `Visit [the docs](${LINK_URL}) for more.`,
].join('\n');

// Lots of message lines so the column actually has overflow.
const FILLER_LINES = Array.from(
  { length: 30 },
  (_, i) => `Filler line ${i + 1} — autogenerated to grow the scroll column.`
);

const STREAM_SCRIPT = [
  ...FILLER_LINES.map(line => ({ text: line + '\n', delayMs: 5 })),
  { text: '\n', delayMs: 5 },
  { text: REPLY_MARKDOWN, delayMs: 10 },
  { finish: 'stop' },
];

async function clickByTitle(title: string, timeoutMs = 6_000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const clicked = await browser.execute((t: string) => {
      const el = document.querySelector(`button[title=${JSON.stringify(t)}]`) as
        | HTMLButtonElement
        | null;
      if (!el) return false;
      el.click();
      return true;
    }, title);
    if (clicked) return true;
    await browser.pause(200);
  }
  return false;
}

async function typeIntoComposer(text: string): Promise<void> {
  await browser.execute((t: string) => {
    const ta = document.querySelector(
      'textarea[placeholder="Type a message..."]'
    ) as HTMLTextAreaElement | null;
    if (!ta) return;
    const setter = Object.getOwnPropertyDescriptor(
      window.HTMLTextAreaElement.prototype,
      'value'
    )?.set;
    setter?.call(ta, t);
    ta.dispatchEvent(new Event('input', { bubbles: true }));
  }, text);
}

async function clickSend(): Promise<boolean> {
  return (await browser.execute(() => {
    const btn = document.querySelector('button[aria-label="Send message"]') as
      | HTMLButtonElement
      | null;
    if (!btn || btn.disabled) return false;
    btn.click();
    return true;
  })) as boolean;
}

// The message column is the `<div ref={messagesContainerRef} className="flex-1 overflow-y-auto ...">`
// in Conversations.tsx. There's only one in /chat so a CSS predicate
// matching the unique `bg-[#f6f6f6]` class is enough.
async function scrollMetrics(): Promise<{
  scrollTop: number;
  scrollHeight: number;
  clientHeight: number;
}> {
  return (await browser.execute(() => {
    const el = document.querySelector(
      'div.flex-1.overflow-y-auto.bg-\\[\\#f6f6f6\\]'
    ) as HTMLElement | null;
    if (!el) return { scrollTop: 0, scrollHeight: 0, clientHeight: 0 };
    return {
      scrollTop: el.scrollTop,
      scrollHeight: el.scrollHeight,
      clientHeight: el.clientHeight,
    };
  })) as { scrollTop: number; scrollHeight: number; clientHeight: number };
}

async function scrollMessageColumn(top: number): Promise<void> {
  await browser.execute((y: number) => {
    const el = document.querySelector(
      'div.flex-1.overflow-y-auto.bg-\\[\\#f6f6f6\\]'
    ) as HTMLElement | null;
    if (el) el.scrollTo({ top: y, behavior: 'auto' });
  }, top);
}

describe('Chat harness — scroll + markdown render', () => {
  before(async () => {
    await startMockServer();
    await waitForApp();
    await resetApp(USER_ID);

    setMockBehavior('llmStreamScript', JSON.stringify(STREAM_SCRIPT));
    setMockBehavior('llmStreamChunkDelayMs', '5');
  });

  after(async () => {
    setMockBehavior('llmStreamScript', '');
    setMockBehavior('llmStreamChunkDelayMs', '');
    await stopMockServer();
  });

  it('streams a long markdown reply', async () => {
    await navigateViaHash('/chat');
    await browser.waitUntil(async () => (await textExists('Threads')), {
      timeout: 15_000,
      timeoutMsg: 'Conversations did not mount',
    });
    expect(await clickByTitle('New thread', 8_000)).toBe(true);

    await typeIntoComposer('Reply with the markdown sample please.');
    expect(
      await browser.waitUntil(async () => await clickSend(), {
        timeout: 5_000,
        timeoutMsg: 'Send button never enabled',
      })
    ).toBe(true);

    // Both canaries must arrive — bold + code block.
    await browser.waitUntil(async () => await textExists(CANARY_BOLD), {
      timeout: 40_000,
      timeoutMsg: 'bold canary never landed',
    });
    await browser.waitUntil(async () => await textExists(CANARY_CODE), {
      timeout: 20_000,
      timeoutMsg: 'code canary never landed',
    });
  });

  it('renders bold as <strong>, fenced code as <pre><code>, links as <a>', async () => {
    const tags = await browser.execute(
      (boldCanary: string, codeCanary: string, linkUrl: string) => {
        const strongs = Array.from(document.querySelectorAll('strong')).map(
          s => s.textContent ?? ''
        );
        const codes = Array.from(document.querySelectorAll('pre code, pre')).map(
          c => c.textContent ?? ''
        );
        const anchors = Array.from(document.querySelectorAll('a[href]')).map(a => ({
          href: (a as HTMLAnchorElement).getAttribute('href') ?? '',
          text: a.textContent ?? '',
        }));
        return {
          hasBold: strongs.some(t => t.includes(boldCanary)),
          hasCode: codes.some(t => t.includes(codeCanary)),
          hasLink: anchors.some(a => a.href === linkUrl),
        };
      },
      CANARY_BOLD,
      CANARY_CODE,
      LINK_URL
    );
    expect(tags.hasBold).toBe(true);
    expect(tags.hasCode).toBe(true);
    expect(tags.hasLink).toBe(true);
  });

  it('auto-scrolls to the bottom while messages arrive', async () => {
    // After all the filler + markdown lands, the column should sit
    // near the bottom (within 16px to absorb sub-pixel layout drift).
    const m = await scrollMetrics();
    expect(m.scrollHeight).toBeGreaterThan(m.clientHeight);
    expect(m.scrollHeight - (m.scrollTop + m.clientHeight)).toBeLessThan(40);
  });

  it('releases the auto-stick when the user scrolls up', async () => {
    // Scroll up by half the column height and prove the auto-stick
    // doesn't yank us back to the bottom.
    const before = await scrollMetrics();
    const targetTop = Math.max(0, before.scrollTop - Math.floor(before.clientHeight / 2));
    await scrollMessageColumn(targetTop);

    // Give the stick hook a few frames to react.
    await browser.pause(500);
    const after = await scrollMetrics();
    expect(Math.abs(after.scrollTop - targetTop)).toBeLessThan(40);
    // And we're now NOT at the bottom.
    expect(after.scrollHeight - (after.scrollTop + after.clientHeight)).toBeGreaterThan(50);
  });
});
