//! Aggregated integration-test target for the `tests/raw_coverage/` suites.
//!
//! Each `tests/raw_coverage/*_raw_coverage_e2e.rs` file is included here as a
//! module instead of being its own `tests/*.rs` target. Cargo builds one test
//! binary for this file rather than ~76, so the (large) `openhuman` rlib is
//! linked once instead of once per file. The module list is generated by
//! `build.rs` (see `raw_coverage_mods.rs`) so new files are picked up
//! automatically.
//!
//! Each included file keeps its own `#![cfg(...)]` gates — as module-level
//! inner attributes they conditionally compile just that module, matching the
//! per-target behaviour these files had as standalone binaries.

// Helper fns/imports that were "used" inside a file's own standalone test
// binary can read as dead once every file shares one crate root here (e.g. a
// helper only reached by a `#[cfg]`-gated test). These are coverage suites, not
// production code, so silence the noise rather than churn 76 files.
#![allow(dead_code, unused_imports)]

include!(concat!(env!("OUT_DIR"), "/raw_coverage_mods.rs"));
