//! Auth, Channels, and Team capability entries.

use super::*;

pub(super) const CAPABILITIES: &[Capability] = &[
Capability {
        id: "team.create",
        name: "Create Teams",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Create a team and start collaborating with shared billing and members.",
        how_to: "Settings > Team",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "team.join_via_invite_code",
        name: "Join Teams via Invite Code",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Join an existing team using an invite code.",
        how_to: "Invites > Redeem an Invite Code",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "team.switch_active_team",
        name: "Switch Active Team",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Switch which team is currently active in the app.",
        how_to: "Settings > Team",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "team.leave",
        name: "Leave Teams",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Leave a team that you no longer want to participate in.",
        how_to: "Settings > Team",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "team.manage_members",
        name: "Manage Team Members",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Review members and change team roles when you have permission.",
        how_to: "Settings > Team > Manage team > Members",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "team.generate_invite_codes",
        name: "Generate Invite Codes",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Create invite codes to bring new members into a team.",
        how_to: "Settings > Team > Manage team > Invites",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "team.track_invite_usage",
        name: "Track Invite Usage",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "View invite usage counts, limits, and revoke team invites.",
        how_to: "Settings > Team > Manage team > Invites",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "auth.login_oauth",
        name: "Login via OAuth",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Sign in with the app's supported provider-based authentication flow.",
        how_to: "Welcome",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "auth.onboarding_setup",
        name: "Onboarding Setup",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Walk through onboarding to configure initial permissions and preferences.",
        how_to: "Onboarding",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "auth.configure_tool_access",
        name: "Configure Tool Access",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Choose which built-in tools OpenHuman can use on your behalf during setup.",
        how_to: "Onboarding > Enable Tools",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "auth.backup_recovery_phrase",
        name: "Back Up Recovery Phrase",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Generate and save a recovery phrase used to secure and restore encrypted app data.",
        how_to: "Onboarding > Recovery Phrase",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "auth.import_recovery_phrase",
        name: "Import Recovery Phrase",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Import an existing recovery phrase to restore encrypted app data.",
        how_to: "Onboarding > Recovery Phrase > I already have a recovery phrase",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "auth.logout",
        name: "Logout",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Sign out of the current session.",
        how_to: "Settings > Log out",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
Capability {
        id: "channels.connect_platform",
        name: "Connect Messaging Platforms",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Connect supported messaging platforms such as Telegram or Discord.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
Capability {
        id: "channels.telegram_remote_control",
        name: "Telegram Remote Control",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description:
            "Operate OpenHuman from Telegram with slash commands: /status, /sessions, /new, and /help.",
        how_to: "Connections > Channels > Telegram (connect), then message the bot",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
Capability {
        id: "channels.disconnect_platform",
        name: "Disconnect Messaging Platforms",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Disconnect a previously configured messaging platform.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
Capability {
        id: "channels.test_credentials",
        name: "Test Channel Credentials",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Validate platform credentials or connection state before using a channel.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
Capability {
        id: "channels.set_default_channel",
        name: "Set Default Messaging Channel",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Choose which messaging channel should be used by default.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
Capability {
        id: "channels.whatsapp_read_messages",
        name: "Read WhatsApp Messages",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Read and search WhatsApp Web conversations and messages after connecting WhatsApp in OpenHuman. Data is stored locally only and never transmitted.",
        how_to: "Connect WhatsApp Web via Channels, then ask the agent to read or summarise your messages.",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_RAW,
    },
Capability {
        id: "channels.mcp_registry_browse",
        name: "Browse MCP Server Registry",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Search and discover MCP servers from the Smithery.ai and official modelcontextprotocol registries.",
        how_to: "Skills > MCP > Browse catalog",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Metadata,
            destinations: &["Smithery.ai registry API", "modelcontextprotocol registry API"],
        }),
    },
Capability {
        id: "channels.mcp_server_install",
        name: "Install MCP Servers",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Install MCP servers locally — both local stdio subprocesses and hosted HTTP-remote servers. Required env vars are stored encrypted and never included in logs or responses. Can also be done conversationally via the MCP setup assistant.",
        how_to: "Skills > MCP > Browse catalog > Install, or ask the assistant to \"set up the <name> MCP server\"",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_CREDENTIALS,
    },
Capability {
        id: "channels.mcp_server_connect",
        name: "Connect / Reconfigure MCP Servers",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Spawn and manage MCP server connections (stdio subprocess or HTTP-remote). Reconfigure stored env vars and reconnect without uninstalling.",
        how_to: "Skills > MCP > select a server > Connect / Reconfigure",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Derived,
            destinations: &["Configured MCP endpoint(s)"],
        }),
    },
Capability {
        id: "channels.mcp_connection_alerts",
        name: "MCP Connection Health Alerts",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Watch installed MCP servers in the background. Each non-nominal liveness-probe outcome (a slow answer, a dropped transport, a reconnect that succeeded or failed) is recorded in the developer Event Log — an answered probe is not, so a healthy server stays silent — and a server that stays down, comes back after failing, or cannot start because its launcher runtime is missing raises a notification.",
        how_to: "Automatic. Settings > Developer > Event Log (filter: mcp) for the stream; Notifications for the alerts",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
Capability {
        id: "channels.mcp_tool_call",
        name: "Invoke MCP Server Tools",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Call tools exposed by connected MCP servers. Tools are surfaced to the agent and runnable from the tool playground.",
        how_to: "Skills > MCP > select a connected server > Tools > Try, or ask the assistant in Chat",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Derived,
            destinations: &["Configured MCP endpoint(s)"],
        }),
    },
];
