//! Compatibility fixtures: bytes written by the pre-`SecretStore`-port code.
//!
//! `fixtures/secrets_enc.bin` and `fixtures/enc2_values.txt` were generated by
//! `EncryptedFileBackend` and `crypto::encrypt_enc2` BEFORE the keyring
//! backends became adapters over `tinystoragedrivers`' `SecretStore`, and were
//! committed untouched. They pin the on-disk formats: a user upgrading must
//! still read every secret, and a downgrade must still read what the new code
//! writes. Never regenerate them to make a test pass.

use super::*;
use tinystoragedrivers::secrets::crypto;

const FIXTURE_KEY: [u8; 32] = [0x42; 32];
const SECRETS_ENC: &[u8] = include_bytes!("fixtures/secrets_enc.bin");
const ENC2_VALUES: &str = include_str!("fixtures/enc2_values.txt");

fn fixture_dir() -> tempfile::TempDir {
    let dir = tempfile::TempDir::new().unwrap();
    std::fs::write(dir.path().join("secrets.enc"), SECRETS_ENC).unwrap();
    dir
}

#[test]
fn enc2_fixture_values_decrypt_under_the_fixture_key() {
    let plain: Vec<String> = ENC2_VALUES
        .lines()
        .map(|line| {
            assert!(line.starts_with("enc2:"));
            String::from_utf8(crypto::decrypt_enc2(&FIXTURE_KEY, line).unwrap().to_vec()).unwrap()
        })
        .collect();
    assert_eq!(plain, ["sk-test-fixture-value", "pa\u{00df}word \u{1f511}"]);
}

#[test]
fn secrets_enc_fixture_reads_through_the_backend() {
    let dir = fixture_dir();
    let backend = EncryptedFileBackend::new(dir.path());
    let get = |k: &str| backend.get_with_key(&FIXTURE_KEY, k).unwrap();
    assert_eq!(get("user-1:session_token").as_deref(), Some("tok-abc-123"));
    assert_eq!(
        get("user-1:api_key").as_deref(),
        Some("sk-fixture-\u{00e9}\u{4e2d}")
    );
    assert_eq!(get("user-2:session_token").as_deref(), Some("tok-other"));
    assert_eq!(get("user-1:missing"), None);
}

#[test]
fn secrets_enc_fixture_survives_a_write_and_stays_in_format() {
    let dir = fixture_dir();
    let backend = EncryptedFileBackend::new(dir.path());
    backend
        .set_with_key(&FIXTURE_KEY, "user-3:new", "added")
        .unwrap();
    // The file is still one raw `nonce || ciphertext || tag` blob over a JSON
    // object of strings, holding the old entries and the new one.
    let blob = std::fs::read(dir.path().join("secrets.enc")).unwrap();
    let json = crypto::decrypt(&FIXTURE_KEY, &blob).unwrap();
    let map: std::collections::BTreeMap<String, String> = serde_json::from_slice(&json).unwrap();
    assert_eq!(map.len(), 4);
    assert_eq!(map["user-3:new"], "added");
    assert_eq!(map["user-1:session_token"], "tok-abc-123");
}
